### GET request to example server
POST localhost:8085/auth/register
content-type: application/json

{
  "email": "laila@example.com",
  "name": "laila",
  "phoneNumber": "0612345678",
  "password": "laila",
  "role": "ADMIN"
}


###